### PR TITLE
Fix some trivial issues learned on real project

### PR DESCRIPTION
**Pull request by tan9**
We are currently evaluating using spring-boot-migrator on our legacy applications and encountering some trivial exceptions. Hope this pull request helps make this project more robust.

### CODE REVIEW

**Comment by tan9** [comment]
@fabapp2 would you please approve me as a first-time contributor to run workflows?

**Comment by sanagaraj-pivotal** [comment]
@tan9 Welcome to Spring Boot Migrator. Thanks for the commit 🎉

**Comment by tan9** [comment]
Hi @sanagaraj-pivotal , the problem is that I can't manage to pass all tests in `main` on my local machine like:

```java
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.springframework.sbm.jee.jsf.recipes.AddJoinfacesDependencies_MyFaces_Test
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AddJmsConfigTest.testAddJmsConfig:122 [

Here's the diff between 1. (---) actual and 2. (+++) expected:

--- package com.example.foo;

import javax.jms.ConnectionFactory;


import org.springframework.boot.autoconfigure.jms.DefaultJmsListenerContainerFactoryConfigurer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jms.annotation.EnableJms;
import org.springframework.jms.config.DefaultJmsListenerContainerFactory;
import org.springframework.jms.config.JmsListenerContainerFactory;
```

Am I missing something? I am using OpenJDK 17.0.5

**Comment by tan9** [comment]
@fabapp2  I have had rebase this branch onto main and passed all the tests, would you please provide some feedback :)

**Comment by fabapp2** [comment]
HI @tan9 

thank you for your contribution 🚀 
... and sorry for my bad responsiveness, I've been on vacation and got a pile of work.

Your PR made me write a test for 
`BuildFile.getDeclaredDependencies()`
`BuildFile.getRequestedDependencies()` 
and `BuildFile.getEffectiveDependencies()` with a multi-module setup which unfortunately surfaced some more issues.

**Review by fabapp2 — APPROVED** [review]
Thank you for your contribution @tan9 🚀

**Comment by fabapp2** [comment]
Hi @tan9 

You added a comment `requested dependency from another module in this multi-module project won't be resolvable`. 
I am not sure what exactly your intent was but from your comment, it looks to me like `getEffectiveDependencies` would be the method you need maybe?

**Comment by fabapp2** [comment]
Hi @tan9 

I deleted my previous comment as I misunderstood your problem. 
My test were failing because of an invalid `artifactId` that I created but after fixing this dependencies to modules in the same multi-module project were properly resolved and
```
if (dependencies.isEmpty()) {
    // requested dependency from another module in this multi-module project won't be resolvable
    return d;
}
```
 was not required.
 
Could you maybe provide an example that made you add this if block? 
I would like to see if my test (not pushed yet, probably tomorrow) is no enough or if there's another reason that made you add this and if there's an issue my test doesn't surface.

**Comment by tan9** [comment]
@fabapp2 All I can remember right now was described in the comment:

> requested dependency from another module in this multi-module project won't be resolvable

If we are working on `ear` packaging module to assemble one or more `war` packaging module, the `war` module somehow won't be resolvable from `getPom(),findDendendepcies()` call, hence returning empty `dependencies`, causing `dependenceis.get(0)` to throw  `IndexOutOfBoundsException.`

Please let me know if the information above is enough to spot the root cause, Or I can try to reproduce this issue and give more details later today or tomorrow.

**Comment by fabapp2** [comment]
Hi @tan9 

That's valuable insight, thank you!
As we're mostly focussing on Boot applications at the moment we might just not have realized this problem.
Actually, there's a good chance that I'd need to discuss this with the people from OpenRewrite who are doing the heavy lifting here. I will try with a JEE setup using ear and war and see if I can reproduce this problem. 
It is not the current focus (which is the Boot 3 Upgrade report) but I will create a new issue for this and look into it.
I am excited that you're using SBM with a real JEE application (they are hard to find publicly). 
So, please keep us posted about issues and problems you might encounter.

**Comment by fabapp2** [comment]
I added #516 to progress on this

**Comment by tan9** [comment]
@fabapp2  I am glad that I can help.

I am going to migrate tons of Java EE projects (100+) that are all tight to Spring Framework 3 under Java 6. We tried using TypeScript to migrate our projects with little success. However, due to the leak of AST, we cannot do further refactoring in an effortless way. Until I read SBM from the [Preparing for Spring Boot 3.0](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0) blog post.

Thanks to all of you guys working on this project, I will try my best to make this project more robust against our legacy and fragile projects :)

**Pull request merged**
