### PR TITLE
Migrate Cassandra configuration to Spring Boot 3.0 in properties format

### LINKED ISSUE #442: 3.0.0-M5: Cassandra Properties
from the [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#cassandra-properties)

>Configuration Properties for Cassandra have moved from `spring.data.cassandra.` to `spring.cassandra.`.

## What needs to be done
Find all properties with prefix `spring.data.cassandra.` and change the prefix to `spring.cassandra.`

**This should be done as (integrated) declarative plain OpenRewrite recipe**

See: 
https://github.com/spring-projects-experimental/spring-boot-migrator/blob/f219382c2b3e4ddffe8efed7b6c0ebe2e96f363c/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/boot-2.7-3.0-dependency-version-update.yaml#L82-L95

### PR DESCRIPTION
**Pull request by kuldeepsidhu88**
Migrate Cassandra configuration to Spring Boot 3.0 in properties format
Fixes #442

### CODE REVIEW

**Comment by fabapp2** [comment]
Hi @kuldeepsidhu88 

thank you for this contribution 🚀 
I will review your PR asap, I was on vacation and am a bit behind.

**Comment by fabapp2** [comment]
Hi @kuldeepsidhu88 

Nice, thank you 👍 

Could you replace the `Visitor` with
````yaml
          - org.openrewrite.properties.ChangePropertyKey:
              oldPropertyKey: spring.data.cassandra
              newPropertyKey: spring.cassandra   
````
which will do the same as the `yaml` but for `properties` files
Sorry, my bad as I didn't add this in the spec. 🙈

**Comment by fabapp2** [comment]
Hi @kuldeepsidhu88 

Forgive me, I wanted to be nice and used the GitHub UI to resolve a merge conflict but broke the integration test leaving a `)`.  🙈 
Shouldn't be hard to fix but I decided not to push anything to your PR.

**Comment by kuldeepsidhu88** [comment]
@fabapp2 Tried with the 

> Hi @kuldeepsidhu88
> 
> Nice, thank you 👍
> 
> Could you replace the `Visitor` with
> 
> ```yaml
>           - org.openrewrite.properties.ChangePropertyKey:
>               oldPropertyKey: spring.data.cassandra
>               newPropertyKey: spring.cassandra   
> ```
> 
> which will do the same as the `yaml` but for `properties` files Sorry, my bad as I didn't add this in the spec. 🙈

I tried as above but test is failing and it does not remove the _data_ property. Please let me know if I am missing something.

image

**Comment by fabapp2** [comment]
> @fabapp2 Tried with the
> 
> > Hi @kuldeepsidhu88
> > Nice, thank you 👍
> > Could you replace the `Visitor` with
> > ```yaml
> >           - org.openrewrite.properties.ChangePropertyKey:
> >               oldPropertyKey: spring.data.cassandra
> >               newPropertyKey: spring.cassandra   
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which will do the same as the `yaml` but for `properties` files Sorry, my bad as I didn't add this in the spec. 🙈
> 
> I tried as above but test is failing and it does not remove the _data_ property. Please let me know if I am missing something. Noticed, this works fine if we provide the full property name.
> 
> image

Hm, I share your observation. 
Maybe I had a bad day yesterday (well possible) or I did something differently.
Need to further investigate. Will ping you when I found the issue.

**Comment by fabapp2** [comment]
Hi @kuldeepsidhu88 

you know what... let's keep your visitor and get this into main?

**Comment by kuldeepsidhu88** [comment]
> Hi @kuldeepsidhu88
> 
> you know what... let's keep your visitor and get this into main?

Sure, changed the PR status from Draft to Open. If no other changes required on this PR, feel free to merge it.

**Review by fabapp2 — APPROVED** [review]
Thank you for your contribution @kuldeepsidhu88 🚀

**Pull request merged**
