### PR TITLE
Fix calculation of base package

### PR DESCRIPTION
**Pull request by soumyaPrakashB**
This is the fix for the issue https://github.com/spring-projects-experimental/spring-boot-migrator/issues/49. Please let me know if any further changes are required.

### CODE REVIEW

**Comment by soumyaPrakashB** [comment]
Hi @fabapp2, I am new to opensource. Forgive my naïveté, do I need to do anything else regarding this PR? Kindly let me know. Thanks.

**Review by fabapp2 — CHANGES_REQUESTED** [review]
Thanks for your contribution @soumyaPrakashB 🚀 

Could you modify one test and add another one as in [this commit](https://github.com/spring-projects-experimental/spring-boot-migrator/commit/89ef37211ced0454c4f8abb70d45d39cec91d603), please?

**Comment by soumyaPrakashB** [comment]
Hi Fabian, included the requested changes. Please review.

**Review by fabapp2 — APPROVED** [review]
Thanks for your contribution @soumyaPrakashB 🚀

**Pull request merged**
